cleanDestinationDir: true
defaultContentLanguage: "en"
disableHugoGeneratorInject: true
enableMissingTranslationPlaceholders: true
removePathAccents: true

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap-v2.xml

markup:
  goldmark:
    renderer:
      unsafe: true

languages:
  en:
    baseURL: "https://www.jedrasiak.eu"
    languageName: english
    weight: 1
    title: "lukasz jedrasiak"
    params:
      domain: "jedrasiak.eu"
      trackingURL: https://plausible.io/js/script.js
    menu:
      main:
      - name: "projects"
        pageRef: /projects/
        weight: 10
      - name: "tools"
        pageRef: /tools/
        weight: 20
      - name: "knowledge"
        pageRef: /knowledge/
        weight: 30
      - name: "blog"
        pageRef: /blog/
        weight: 40
      - name: "contact"
        pageRef: /contact/
        weight: 50

  pl:
    baseURL: "https://www.jedrasiak.pl"
    languageName: polski
    weight: 2
    title: "łukasz jędrasiak"
    params:
      domain: "jedrasiak.pl"
      trackingURL: https://plausible.io/js/script.js
    menu:
      main:
      - name: "projekty"
        pageRef: /projekty/
        weight: 10
      - name: "narzędzia"
        pageRef: /narzedzia/
        weight: 20
      - name: "wiedza"
        pageRef: /baza-wiedzy/
        weight: 30
      - name: "blog"
        pageRef: /blog/
        weight: 40
      - name: "kontakt"
        pageRef: /kontakt/
        weight: 50