cleanDestinationDir: true
defaultContentLanguage: "en"
disableHugoGeneratorInject: true
enableMissingTranslationPlaceholders: true
removePathAccents: true

sitemap:
  changefreq: monthly
  priority: 0.5

languages:
  en:
    baseURL: "https://www.jedrasiak.eu"
    languageName: english
    weight: 1
    title: "lukasz jedrasiak"
    menu:
      main:
      - name: "projects"
        pageRef: /projects
        weight: 10
      - name: "tools"
        pageRef: /tools
        weight: 20
      - name: "knowledge"
        pageRef: /knowledge
        weight: 30
      - name: "newsletter"
        pageRef: /newsletter
        weight: 40
      - name: "hire me"
        pageRef: /contact
        weight: 50

  pl:
    baseURL: "https://www.jedrasiak.pl"
    languageName: polski
    weight: 2
    title: "łukasz jędrasiak"
    menu:
      main:
      - name: "projekty"
        pageRef: /projekty
        weight: 10
      - name: "narzędzia"
        pageRef: /narzedzia
        weight: 20
      - name: "wiedza"
        pageRef: /baza-wiedzy
        weight: 30
      - name: "newsletter"
        pageRef: /newsletter
        weight: 40
      - name: "zatrudnij mnie"
        pageRef: /kontakt
        weight: 50